configpath: ""
output: json
outputtemplatefile: ""
scopeopt: ""
scope: Squashed
quiet: false
log:
    structured: false
    levelopt: 0
    level: trace
    filelocation: ""
clioptions:
    verbosity: 0
db:
  auto-update: false
  cache-dir: "/etc/vuln-scan/anchore-resources/db"
  update-url: "https://toolbox-data.anchore.io/grype/databases/listing.json"
  validatebyhashonstart: false
dev:
    profilecpu: false
checkforappupdate: true
registry:
    insecure-skip-tls-verify: false
    insecure-use-http: false
    auth: []
